# Site settings
title: Actualidade
email: your-email@domain.com
url: "http://localhost:4000/"
description: "Actualida.de é uma lista de notícias em língua portuguesa, actualizadado automáticamente."

exclude: ['Gruntfile.js','assets/sass','package.json','README','.gitignore','node_modules']

css: ['https://atualida.de/assets/css/app.min.css','https://atualida.de/assets/css/font-awesome.min.css']
js: ['https://atualida.de/assets/js/libs.js','https://atualida.de/assets/js/app.js']
img: []


