# Site settings
title: Your awesome title
email: your-email@domain.com
url: "http://localhost:4000/"
description: "stuffs about things"

exclude: ['Gruntfile.js','sass','package.json','README','.gitignore','node_modules']

css: ['assets/css/ink.min.css']
js: ['assets/js/libs.js','assets/js/app.js']
img: []


